name: diff

on:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create diff
        run: |
          ./gendiff
      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        with:
          name: index
          path: _output/http/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _output/http
          CLEAN: true
          GIT_CONFIG_EMAIL: 21696493+fntlnzbot@users.noreply.github.com
          GIT_CONFIG_NAME: fntlnzbot
